
import org.apache.shiro.cas.grails.ShiroCasSecurityFilters
import org.apache.shiro.subject.Subject
import org.codehaus.groovy.grails.plugins.web.filters.FilterConfig
import org.apache.shiro.SecurityUtils
import org.template.User

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters extends ShiroCasSecurityFilters{

    def filters = {
        
        admin(controller: 'admin') {
            before = {
                accessControl()
            }
        }
        
        //check to see if user is logged in or not, pass user info to view if logged in, else "guest"
        loggedCheck(controller: '*', action: '*') {
           before = {
               Subject currentUser = SecurityUtils.getSubject();
               if(currentUser && currentUser.isAuthenticated()){
                   def user=User.findByUsername(currentUser.getPrincipal())
                   if(user){
                       request.setAttribute('current_user',user.getFullName())
                   }
                   else{
                       request.setAttribute("current_user","Guest")
                   }
               }
               else{
                   request.setAttribute("current_user","Guest")
               }
           }
        }

    }
    
   
    
}
